basic-example:
  imageRepository: "gcr.io/basic-example"
  host: "app.basic-example.ai"

  frontend:
    image:
      tag: "f3b1bc543d12984920c7644c1d64e0aa4b024de7"

  backend:
    image:
      tag: "f3b1bc543d12984920c7644c1d64e0aa4b024de7"

  environment:
    variables:
      - name: "AUTH0_AUDIENCE"
        value: "https://app.basic-example.ai/api"
      - name: "AUTH0_DOMAIN"
        value: "basic-example.us.auth0.com"