{{- define "common.backendService" -}}
{{- $name := .Values.backend.name | default .Chart.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.backend.name | default .Chart.Name }}
{{- end -}}