{{- define "common.certManager" -}}
{{- $name := .Values.certManager.name | default .Chart.Name -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: jennifer@influenx.ai
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            name: {{ .Values.ingress.name | default .Chart.Name }}

---
# issuer-lets-encrypt-production.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jennifer@influenx.ai
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            name: {{ .Values.ingress.name | default .Chart.Name }}
{{- end -}}
