{{- define "common.database" -}}
{{- $name := .Values.database.name | default .Chart.Name -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}-db
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-db
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}-db
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: {{ $name }}-db
          persistentVolumeClaim:
            claimName: {{ $name }}-db
      containers:
        - name: develop
          image: postgres:latest
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "1Gi"
          volumeMounts:
            - name: {{ $name }}-db
              mountPath: "/var/lib/postgresql/data"
          env:
          - name: POSTGRES_USER
            value: {{ .Values.database.user }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.database.password }}
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-db
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ $name }}-db
{{- end -}}