{{- define "common.database" -}}
{{- $name := .Values.database.name | default (print .Chart.Name "-db") -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  replicas: {{ .Values.database.replicas }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: {{ $name }}
          persistentVolumeClaim:
            claimName: {{ $name }}
      containers:
        - name: {{ $name }}
          image: postgres:latest
          ports:
            - containerPort: {{ .Values.database.port }}
          resources:
            requests:
              memory: {{ .Values.database.memory }}
          volumeMounts:
            - name: {{ $name }}
              mountPath: "/var/lib/postgresql/data"
          env:
          - name: POSTGRES_USER
            value: {{ .Values.database.user }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.database.password }}
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
  selector:
    app: {{ $name }}
{{- end -}}