{{- define "common.frontendDeployment" -}}
{{- if not or (.Values.imageRepository .Values.frontend.image.repository) -}}
{{- fail ".Values.imageRepository or .Values.frontend.image.repository must be defined" -}}
{{- end -}}
{{- $name := .Values.frontend.name | default .Chart.Name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-helm.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influenx-frontend
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default .Chart.Name }}
      containers:
        - name: {{ .Values.frontend.name | default .Chart.Name }}
          image: "gcr.io/influenx-ai-development/influenx-frontend:f3b1bc543d12984920c7644c1d64e0aa4b024de7"
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
{{- end -}}