{{- define "common.frontendService" -}}
{{- $name := .Values.frontend.name | default (print .Chart.Name "-frontend") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.frontend.name | default $name }}
{{- end -}}