{{- define "common.frontendDeployment" -}}
{{- if not (or .Values.imageRepository .Values.frontend.image.repository) -}}
{{- fail ".Values.imageRepository or .Values.frontend.image.repository must be defined" -}}
{{- end -}}
{{- $name := .Values.frontend.name | default (print .Chart.Name "-frontend") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default .Chart.Name }}
      containers:
        - name: {{ $name }}
          image: "{{ .Values.frontend.image.repository | default .Values.imageRepository }}/{{ .Values.frontend.image.name | default $name }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
{{- end -}}