{{- define "common.ingress" -}}
{{- if not .Values.host -}}
{{- fail ".Values.host must be defined" -}}
{{- end -}}
{{- $name := .Values.ingress.name | default .Chart.Name -}}
{{- $frontendName := .Values.frontend.name | default (print .Chart.Name "-frontend") -}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ $name }}-ssl-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "{{ $name }}-ip"
    kubernetes.io/ingress.class: gce
    networking.gke.io/v1beta1.FrontendConfig: {{ $name }}-ssl-config
    cert-manager.io/issuer: letsencrypt-production
spec:
  tls:
    - secretName: {{ $name }}-ssl-config
      hosts:
        - {{ .Values.host }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{- .Values.ingress.service | default $frontendName -}}
                port:
                  number: {{ .Values.frontend.port }}
{{- end -}}