{{- define "common.serviceAccount" -}}
{{- $name := .Values.database.name | default .Chart.Name -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
imagePullSecrets:
  - name: gcr-json-key
{{- end -}}
