# Default values for common chart.

# -- GCR image repo to pull from for all deployments in this chart. Frontend and backend deployments can be overridden
# under their settings
imageRepository: ""
# -- External host to use for app
host: ""

backend:
  # -- Turn this on to create a backend deployment resource. Most likely you want this ON
  enabled: true
  # -- Can overwrite backend deployment name. Defaults to chart name+ "-backend"
  # @default -- `{{ .Chart.Name }}-backend`
  name: ""
  # -- Backend image port
  port: 80
  # -- Backend external port
  targetPort: 3001
  image:
    # -- Can overwrite image name. Defaults to chart name + "-backend"
    # @default -- `{{ .Chart.Name }}-backend`
    name: ""
    # -- Can overwrite backend image repository. Defaults to .Values.imageRepository
    # @default -- `.Values.imageRepository`
    repository: ""
    # -- The tag of the image. This will most likely need to be overridden at runtime.
    tag: "latest"
  resources:
    # -- Memory for pods
    memory: "512Mi"
    # -- CPU for pods
    cpu: "200m"
    # -- limitMemory for pods
    limitMemory: "700Mi"
    # -- limitCPU for pods
    limitCPU: "300m"

frontend:
  # -- Turn this on to create a frontend deployment resource
  enabled: true
  # -- Can overwrite backend deployment name. Defaults to chart name + "-frontend"
  # @default -- `{{ .Chart.Name }}-frontend`
  name: ""
  # -- Frontend image port
  port: 80
  # -- Frontend external port
  targetPort: 3000
  image:
    # -- Can overwrite image name. Defaults to chart name + "-frontend"
    # @default -- `{{ .Chart.Name }}-frontend`
    name: ""
    # -- Can overwrite frontend image repository. Defaults to .Values.imageRepository
    # @default -- `.Values.imageRepository`
    repository: ""
    # -- The tag of the image. This will most likely need to be overridden at runtime.
    tag: "latest"
  resources:
    # -- Memory for pods
    memory: "128Mi"
    # -- CPU for pods
    cpu: "100m"
    # -- limitMemory for pods
    limitMemory: "256Mi"
    # -- limitCPU for pods
    limitCPU: "200m"

serviceAccount:
  # -- Turn this on to create a serviceAccount resource. Most likely you want this ON
  enabled: true
  # -- Can overwrite serviceAccount name. Defaults to chart name
  # @default -- `{{ .Chart.Name }}`
  name: ""
  # -- GCR secret used to authenticate and pull images from Google
  imagePullSecrets: gcr-json-key

ingress:
  # -- Turn this on to create a ingress resource. Most likely you want this ON
  enabled: true
  # -- Can overwrite serviceAccount name. Defaults to chart name
  # @default -- `{{ .Chart.Name }}`
  name: ""
  # -- What service should this ingress point to? Defaults to the frontend service
  # @default -- `{{ .frontend.name }}`
  service: ""
  # -- Port to expose
  port: "80"

database:
  # -- Turn this on to create a database resource. Right now this will only be postgres
  enabled: true
  # -- Can overwrite serviceAccount name. Defaults to chart name + "-db"
  # @default -- `{{ .Chart.Name }}-db`
  name: ""
  # -- Number of pod replicas
  replicas: 1
  # -- Port to expose. By default postgres uses 5432
  port: 5432
  # -- Database storage
  storage: 20Gi
  # -- Database memory
  memory: 1Gi
  # -- Username used to access the database
  user: "postgres"
  # TODO: We should probably grab this from a Secret
  # -- Password used to access the database
  password: "postgres"
  # -- Name of the database to be created
  # @default -- `{{ .Chart.Name }}-db`
  database_name: ""

# TODO: Will need to flesh this out later
certManager:
  # -- Turn this on to create needed Issuer resources. Most likely you want this ON
  enabled: true

environment:
  # -- List of variables you want to use throughout the app. This will create a configmap that is pulled in to all deployments
  variables: []
  # Example of use
  #    - name: REPLAY_OPENSEARCH_ADDR
  #      value: "foobar"
  # -- Set this to pull in a Secret to the deployment
  secret: ""

# TODO: Will need to flesh this out later
autoscaling:
  enabled: false
  hpaName: ""
  replicaCount: 1
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# TODO: Will need to flesh this out later
test:
  enabled: false
  name: ""